export enum TipoOperacionPppoe {
  CREAR_SECRET = 'CREAR_SECRET',
  ACTIVAR_SECRET = 'ACTIVAR_SECRET',
  SUSPENDER_SERVICIO = 'SUSPENDER_SERVICIO',
  ELIMINAR_SECRET = 'ELIMINAR_SECRET',
}

export enum CanalOperacionPppoe {
  SSH = 'SSH',
  ROUTEROS_API = 'ROUTEROS_API',
  MANUAL = 'MANUAL',
}

export enum EstadoOperacionPppoe {
  PENDIENTE = 'PENDIENTE',
  AUTORIZADA = 'AUTORIZADA',
  EJECUTANDO = 'EJECUTANDO',
  EXITOSA = 'EXITOSA',
  PARCIAL = 'PARCIAL',
  FALLIDA = 'FALLIDA',
  CANCELADA = 'CANCELADA',
}

export enum TipoPasoPppoe {
  CONECTAR_ROUTER = 'CONECTAR_ROUTER',
  BUSCAR_SECRET = 'BUSCAR_SECRET',
  AGREGAR_SECRET = 'AGREGAR_SECRET',
  CONFIRMAR_SECRET = 'CONFIRMAR_SECRET',
  HABILITAR_SECRET = 'HABILITAR_SECRET',
  DESHABILITAR_SECRET = 'DESHABILITAR_SECRET',
  REMOVER_SESION_ACTIVA = 'REMOVER_SESION_ACTIVA',
  ELIMINAR_SECRET = 'ELIMINAR_SECRET',
}

export enum EstadoPasoPppoe {
  PENDIENTE = 'PENDIENTE',
  EJECUTANDO = 'EJECUTANDO',
  EXITOSO = 'EXITOSO',
  FALLIDO = 'FALLIDO',
  OMITIDO = 'OMITIDO',
}
