export const TECNICO_TRACKING_REPOSITORY = Symbol(
  'TECNICO_TRACKING_REPOSITORY',
);

export const ASISTENCIA_TRACKING_PORT = Symbol('ASISTENCIA_TRACKING_PORT');

export const TECNICO_TRACKING_QUERY = Symbol('TECNICO_TRACKING_QUERY');

export const TECNICO_TRACKING_REALTIME = Symbol('TECNICO_TRACKING_REALTIME');
