export enum MotivoDesinstalacionCliente {
  VOLUNTARIA = 'VOLUNTARIA',
  MORA = 'MORA',
  CAMBIO_DOMICILIO = 'CAMBIO_DOMICILIO',
  MAL_SERVICIO = 'MAL_SERVICIO',
  FRAUDE = 'FRAUDE',
  FALLA_TECNICA = 'FALLA_TECNICA',
  CAMBIO_PROVEEDOR = 'CAMBIO_PROVEEDOR',
  CLIENTE_NO_LOCALIZADO = 'CLIENTE_NO_LOCALIZADO',
  OTRO = 'OTRO',
}
