export enum TipoDesinstalacionCliente {
  COMPLETA = 'COMPLETA',
  PARCIAL = 'PARCIAL',
  RETIRO_EQUIPO = 'RETIRO_EQUIPO',
  CAMBIO_DOMICILIO = 'CAMBIO_DOMICILIO',
  CANCELACION_SERVICIO = 'CANCELACION_SERVICIO',
  OTRO = 'OTRO',
}
