export enum EstadoInstalacionCliente {
  PROGRAMADA = 'PROGRAMADA',
  EN_PROCESO = 'EN_PROCESO',
  COMPLETADA = 'COMPLETADA',
  CANCELADA = 'CANCELADA',
  FALLIDA = 'FALLIDA',
  REPROGRAMADA = 'REPROGRAMADA',
}
