export enum TipoInstalacionCliente {
  NUEVA = 'NUEVA',
  REINSTALACION = 'REINSTALACION',
  TRASLADO = 'TRASLADO',
  CAMBIO_EQUIPO = 'CAMBIO_EQUIPO',
  MIGRACION_PLAN = 'MIGRACION_PLAN',
  MIGRACION_TECNOLOGIA = 'MIGRACION_TECNOLOGIA',
  OTRO = 'OTRO',
}
