export enum TipoEvidenciaClienteOperacion {
  ANTES = 'ANTES',
  DESPUES = 'DESPUES',
  EQUIPO = 'EQUIPO',
  ROUTER = 'ROUTER',
  ONU = 'ONU',
  ANTENA = 'ANTENA',
  CABLEADO = 'CABLEADO',
  UBICACION = 'UBICACION',
  FIRMA = 'FIRMA',
  BOLETA = 'BOLETA',
  RECIBO = 'RECIBO',
  DOCUMENTO = 'DOCUMENTO',
  OTRO = 'OTRO',
}

export enum CategoriaMedia {
  CLIENTE_GENERAL = 'CLIENTE_GENERAL',
  CLIENTE_CONTRATO = 'CLIENTE_CONTRATO',
  CLIENTE_INSTALACION = 'CLIENTE_INSTALACION',
  CLIENTE_DESINSTALACION = 'CLIENTE_DESINSTALACION',
  CLIENTE_ELIMINACION = 'CLIENTE_ELIMINACION',
  SOPORTE_TICKET = 'SOPORTE_TICKET',
  OTRO = 'OTRO',
}

export enum TipoMedia {
  IMAGEN = 'IMAGEN',
  VIDEO = 'VIDEO',
  DOCUMENTO = 'DOCUMENTO',
  AUDIO = 'AUDIO',
  OTRO = 'OTRO',
}
