export const STORAGE_PORT = Symbol('STORAGE_PORT');
export const MEDIA_REPOSITORY = Symbol('MEDIA_REPOSITORY');
export const SUBIR_MEDIA_USECASE = Symbol('SUBIR_MEDIA_USECASE');
export const SPACES_S3 = Symbol('SPACES_S3');
export const SPACES_CFG = Symbol('SPACES_CFG');
export const ELIMINAR_MEDIA_USECASE = Symbol('ELIMINAR_MEDIA_USECASE');
//REUTILIZABLE
export const UPLOAD_FILE_USECASE = Symbol('UPLOAD_FILE_USECASE');
