export enum EstadoCuentaPppoe {
  PENDIENTE_ACTIVACION = 'PENDIENTE_ACTIVACION',
  EN_INSTALACION = 'EN_INSTALACION',
  EN_ACTIVACION = 'EN_ACTIVACION',
  ACTIVA = 'ACTIVA',
  SUSPENDIDA = 'SUSPENDIDA',
  EN_DESINSTALACION = 'EN_DESINSTALACION',
  ELIMINADA = 'ELIMINADA',
  ERROR = 'ERROR',
}
