// export enum EstadoCuentaPppoe {
//   PENDIENTE_ACTIVACION = 'PENDIENTE_ACTIVACION',
//   EN_INSTALACION = 'EN_INSTALACION',
//   EN_ACTIVACION = 'EN_ACTIVACION',
//   ACTIVA = 'ACTIVA',
//   SUSPENDIDA = 'SUSPENDIDA',
//   EN_DESINSTALACION = 'EN_DESINSTALACION',
//   ELIMINADA = 'ELIMINADA',
//   ERROR = 'ERROR',
// }

export enum EstadoCuentaPppoe {
  PENDIENTE_CREACION = 'PENDIENTE_CREACION',

  EN_INSTALACION = 'EN_INSTALACION',

  PENDIENTE_ACTIVACION = 'PENDIENTE_ACTIVACION',

  EN_ACTIVACION = 'EN_ACTIVACION',

  ACTIVA = 'ACTIVA',

  EN_SUSPENSION = 'EN_SUSPENSION',

  SUSPENDIDA = 'SUSPENDIDA',

  EN_DESINSTALACION = 'EN_DESINSTALACION',

  ELIMINADA = 'ELIMINADA',

  CANCELADA = 'CANCELADA',

  ERROR = 'ERROR',
}
