export const CLIENTE_DESINSTALACION_REPOSITORY = Symbol(
  'CLIENTE_DESINSTALACION_REPOSITORY',
);

export const CLIENTE_DESINSTALACION_AUTORIZACION_REPOSITORY = Symbol(
  'CLIENTE_DESINSTALACION_AUTORIZACION_REPOSITORY',
);

export const CLIENTE_DESINSTALACION_TECNICO_REPOSITORY = Symbol(
  'CLIENTE_DESINSTALACION_TECNICO_REPOSITORY',
);
